---
- name: Get serial numbers
  hosts: clients
  gather_facts: False
  tasks:
    - name: "Get Serial Number"
      community.routeros.command:
        commands:
          - /system license print
      register: license

    - name: "Get Name"
      community.routeros.command:
        commands:
          - /system identity print
      register: identity
    
    - name: Add Serial Number to Netbox
      netbox_device:
        netbox_url: http://87.228.37.211:8000
        netbox_token: token
        data:
          name: "{{ identity.stdout_lines[0][0].split()[1] }}"
          serial: "{{ license.stdout_lines[0][0].split()[1] }}"
